# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :unit_tests do
  	scan
    danger(
      danger_id: "unit-tests",
      dangerfile: "Dangerfile",
      github_api_token: ENV["DANGER_GITHUB_API_TOKEN"],
      verbose: true
    ) 
  	xcov(
		project: "PlanB.xcodeproj",
		minimum_coverage_percentage: 0.0
  	)
  end
end